@URL=http://localhost:8080/login
@TOKEN=
login

###autenticação
POST {{URL}}
Content-Type: application/json

{
    "username" : "user",
    "password" : "senha"
}

####  

POST http://localhost:8080/users
Authorization: Bearer {{TOKEN}}

{

  "username": "user1",
  "email": "emaail@email.com",
  "password": "senha"
}
####  

GET http://localhost:8080/users